import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import { CartProvider } from "./components/cart/CartContext"; // importera CartContext för att kunna använda det

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "GroupOne",
  description: "Generated by GroupOne",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider> {/* wrappar in CartProvider runt layout */}
          <div className="min-h-screen flex flex-col justify-between">
          <Header />
          {children}
          <Footer />
          </div>
        </CartProvider>
      </body>
    </html>
  );
}
